pipeline {
    agent any
    environment {
        IMAGE_NAME = 'art-gallery-jenkins'
        REGISTRY = 'layanga/art-gallery-docker'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Layanga-Rajapakshe/Art-gallery.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat '''
                    cd art-gallery
                    docker build -t %IMAGE_NAME% .
                '''
            }
        }

        stage('Login to Docker Hub & Push Image') {
            steps {
                withDockerRegistry([credentialsId: 'layanga-docker-access', url: 'https://hub.docker.com/repository/docker/layanga/art-gallery-docker/']) {
                    bat '''
                        cd art-gallery
                        docker tag %IMAGE_NAME% %REGISTRY%/%IMAGE_NAME%:latest
                        docker push %REGISTRY%/%IMAGE_NAME%:latest
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                    cd art-gallery
                    docker run -d -p 5173:5173 %REGISTRY%/%IMAGE_NAME%:latest
                '''
            }
        }
    }
}
