pipeline {
    agent any
    environment {
        IMAGE_NAME = 'art-gallery-jenkins'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Layanga-Rajapakshe/Art-gallery.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat '''
                    cd art-gallery
                    docker build -t %IMAGE_NAME% .
                '''
            }
        }


        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'layanga-docker-access', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                bat '''
                    docker push %IMAGE_NAME%:latest
                '''
            }
        }

        stage('Cleanup') {
            steps {
                bat '''
                    docker rmi %IMAGE_NAME%:latest
                '''
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                    cd art-gallery
                    docker run -d -p 5173:5173 %IMAGE_NAME%:latest
                '''
            }
        }
    }
}
